# Generated by Django 5.2.10 on 2026-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this sermon from the public website (draft).'),
        ),
    ]
