# Generated by Django 5.2.10 on 2026-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('general', 'General / fellowship / outreach'), ('seminar_training', 'Seminar & skills training (entrepreneurship, empowerment, etc.)')], db_index=True, default='general', help_text='Use “Seminar & skills training” for entrepreneurship, empowerment, and similar programs.', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='training_focus',
            field=models.CharField(blank=True, help_text='Short label, e.g. Entrepreneurship, Financial literacy, Youth empowerment.', max_length=255),
        ),
    ]
