# Generated by Django 5.2.10 on 2026-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_donors_and_seminars'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this event from the public website (draft).'),
        ),
    ]
