# Generated by Django 5.2.10 on 2026-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Church History',
                'verbose_name_plural': 'Church History',
            },
        ),
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church/logo/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('reverend_name', models.CharField(default='Rev. Samuel Muhindi Mwaura', max_length=255)),
                ('reverend_bio', models.TextField(blank=True)),
                ('reverend_photo', models.ImageField(blank=True, null=True, upload_to='church/reverend/')),
            ],
            options={
                'verbose_name': 'Church Information',
                'verbose_name_plural': 'Church Information',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
