# Generated by Django 5.2.10 on 2026-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Shoes & footwear'), ('toys_children', 'Toys for children'), ('adults', 'Toys & gifts for adults'), ('other', 'Other in-kind gifts')], default='other', max_length=32)),
                ('headline', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True, help_text='Condition, sizes, drop-off instructions, or other notes for donors.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Accepted in-kind donation',
                'verbose_name_plural': 'Accepted in-kind donations',
                'ordering': ['sort_order', 'headline'],
            },
        ),
    ]
