# Generated by Django 5.2.10 on 2026-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donors_and_seminars'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(help_text='e.g. "Wednesday"', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('time_label', models.CharField(help_text='e.g. "3:00 PM - 6:00 PM"', max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Weekly service time',
                'verbose_name_plural': 'Weekly service times',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.RemoveField(
            model_name='accepteddonation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='accepteddonation',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Only published items appear on the public Giving page.'),
        ),
        migrations.AddField(
            model_name='churchhistory',
            name='is_published',
            field=models.BooleanField(default=True, help_text='If unchecked, history is hidden on the public About page.'),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='mpesa_paybill',
            field=models.CharField(blank=True, help_text='M-Pesa business / paybill number.', max_length=32),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='mpesa_paybill_account',
            field=models.CharField(blank=True, help_text='Account name donors should use (e.g. OFFERING).', max_length=64),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='mpesa_till',
            field=models.CharField(blank=True, help_text='M-Pesa till number, if used.', max_length=32),
        ),
        migrations.AddField(
            model_name='churchinfo',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Digits only, no + (e.g. 254712345678) for WhatsApp chat link.', max_length=20),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='is_published',
            field=models.BooleanField(default=True, help_text='If unchecked, this value is hidden on the public About page.'),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
