from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("login/", views.StaffLoginView.as_view(), name="login"),
    path("logout/", views.staff_logout, name="logout"),
    path("", views.home, name="home"),
    path("church/", views.church_info, name="church_info"),
    path("history/", views.church_history, name="church_history"),
    path("sermons/", views.sermon_list, name="sermon_list"),
    path("sermons/add/", views.sermon_add, name="sermon_add"),
    path("sermons/<int:pk>/edit/", views.sermon_edit, name="sermon_edit"),
    path("sermons/<int:pk>/delete/", views.sermon_delete, name="sermon_delete"),
    path("events/", views.event_list, name="event_list"),
    path("events/add/", views.event_add, name="event_add"),
    path("events/<int:pk>/edit/", views.event_edit, name="event_edit"),
    path("events/<int:pk>/delete/", views.event_delete, name="event_delete"),
    path("hero-slides/", views.hero_list, name="hero_list"),
    path("hero-slides/add/", views.hero_add, name="hero_add"),
    path("hero-slides/<int:pk>/edit/", views.hero_edit, name="hero_edit"),
    path("hero-slides/<int:pk>/delete/", views.hero_delete, name="hero_delete"),
    path("service-times/", views.weekly_list, name="weekly_list"),
    path("service-times/add/", views.weekly_add, name="weekly_add"),
    path("service-times/<int:pk>/edit/", views.weekly_edit, name="weekly_edit"),
    path("service-times/<int:pk>/delete/", views.weekly_delete, name="weekly_delete"),
    path("links/", views.social_list, name="social_list"),
    path("links/add/", views.social_add, name="social_add"),
    path("links/<int:pk>/edit/", views.social_edit, name="social_edit"),
    path("links/<int:pk>/delete/", views.social_delete, name="social_delete"),
    path("core-values/", views.value_list, name="value_list"),
    path("core-values/add/", views.value_add, name="value_add"),
    path("core-values/<int:pk>/edit/", views.value_edit, name="value_edit"),
    path("core-values/<int:pk>/delete/", views.value_delete, name="value_delete"),
    path("in-kind-donations/", views.donation_list, name="donation_list"),
    path("in-kind-donations/add/", views.donation_add, name="donation_add"),
    path("in-kind-donations/<int:pk>/edit/", views.donation_edit, name="donation_edit"),
    path("in-kind-donations/<int:pk>/delete/", views.donation_delete, name="donation_delete"),
    path("members/", views.member_list, name="member_list"),
    path("members/add/", views.member_add, name="member_add"),
    path("members/<int:pk>/edit/", views.member_edit, name="member_edit"),
    path("members/<int:pk>/delete/", views.member_delete, name="member_delete"),
    path("prayer/", views.prayer_list, name="prayer_list"),
    path("prayer/<int:pk>/", views.prayer_edit, name="prayer_edit"),
    path("messages/", views.message_list, name="message_list"),
    path("messages/<int:pk>/", views.message_detail, name="message_detail"),
]
