# Generated by Django 5.2.10 on 2026-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='For future public directories; keep checked for active records.'),
        ),
    ]
